# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-01 09:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lottery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField(default=0, verbose_name='Количество денег внесено')),
                ('score', models.IntegerField(default=0, verbose_name='Количество монет')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Счета',
                'verbose_name_plural': 'Счета',
            },
        ),
        migrations.CreateModel(
            name='BillingHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField(default=0, verbose_name='Внесено в денежном эквиваленте')),
                ('score', models.IntegerField(default=0, verbose_name='Внесено монет')),
                ('payment_status', models.CharField(default='proccess', max_length=100, verbose_name='Статус платежа')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'История пополнения',
                'verbose_name_plural': 'История пополнения',
            },
        ),
        migrations.CreateModel(
            name='HistoryGames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('stuff', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lottery.Stuff', verbose_name='Вещь')),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История игр',
                'verbose_name_plural': 'История игр',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lottery.Stuff', verbose_name='Вещь')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Вещи',
                'verbose_name_plural': 'Вещи',
            },
        ),
    ]
