# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-06 19:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userservice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userservice',
            options={'verbose_name': 'Доп. инф. о пользователях', 'verbose_name_plural': 'Доп. инф. о пользователях'},
        ),
    ]
