# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-06 20:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170806_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historygames',
            name='stuff',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='lottery.Stuff', verbose_name='Вещь'),
        ),
        migrations.AlterField(
            model_name='historygames',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
