# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-07 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20170806_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='coins',
            field=models.IntegerField(default=0, verbose_name='Монеты'),
        ),
    ]
