# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-21 02:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0007_stuff_show_shop_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0008_auto_20170813_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopStuff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuff', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='lottery.Stuff', verbose_name='Вещь')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Вещи на продажу',
                'verbose_name_plural': 'Вещи на продажу',
            },
        ),
        migrations.CreateModel(
            name='ShopStuffFavorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuff', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='lottery.Stuff', verbose_name='Вещь')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Избранные вещи',
                'verbose_name_plural': 'Избранные вещи',
            },
        ),
    ]
