# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-23 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_shopstuff_shopstufffavorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='type',
            field=models.CharField(default='games', max_length=20, verbose_name='Способ получения вещи'),
        ),
    ]
