# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-01 09:41
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Текст статьи')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('img', models.FileField(upload_to='', verbose_name='Картинка')),
                ('comments_status', models.BooleanField(default=False, verbose_name='Отображать комментарии')),
                ('views', models.IntegerField(default=0, verbose_name='Количество просмотров')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Статьи',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
