# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-01 09:42
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название страницы')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Текст')),
                ('comments_status', models.BooleanField(default=False, verbose_name='Разрешить комментарии')),
                ('show_status', models.BooleanField(default=True, verbose_name='Показывать страницу')),
            ],
            options={
                'verbose_name': 'Страницы',
                'verbose_name_plural': 'Страницы',
            },
        ),
    ]
