# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-07 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='sales_margin',
            field=models.IntegerField(default=10, verbose_name='Наценка на продажу вещи (%)'),
        ),
    ]
