# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-23 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_auto_20170823_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='enable_shop',
            field=models.BooleanField(default=True, verbose_name='Магазин включен'),
        ),
    ]
