# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-01 09:42
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Заголовок', max_length=100, verbose_name='Заголовок')),
                ('text', ckeditor.fields.RichTextField(default='Описание', verbose_name='Текст')),
                ('img', models.FileField(default='st_img.png', upload_to='', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField(default='Описание', verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Название для видео', max_length=100, verbose_name='Название')),
                ('video_link', models.CharField(default='http://youtube.com/', max_length=200, verbose_name='Ссылка на видео')),
                ('img', models.FileField(default='st_img.png', upload_to='', verbose_name='Картинка')),
                ('created_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
    ]
