# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-01 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Briefcases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Название для кейса', max_length=100, verbose_name='Название')),
                ('type', models.CharField(default='#282840, #f92552', max_length=100, verbose_name='Тип')),
                ('score', models.IntegerField(default=0, verbose_name='Стоимость')),
                ('img', models.FileField(default='st_img.png', upload_to='', verbose_name='Картинка')),
                ('show_main_page_status', models.BooleanField(default=True, verbose_name='Отображать на лвной странице')),
                ('created_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Кейсы',
                'verbose_name_plural': 'Кейсы',
            },
        ),
        migrations.CreateModel(
            name='DotaboxModes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Название', max_length=100, verbose_name='Название режима')),
                ('description', models.TextField(default='Описание', verbose_name='Описание')),
                ('score', models.IntegerField(default=0, verbose_name='Стоимость игры')),
                ('enable', models.BooleanField(default=False, verbose_name='Режим включен')),
            ],
            options={
                'verbose_name': 'Dota Box режимы',
                'verbose_name_plural': 'Dota Box режимы',
            },
        ),
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Название вещей', max_length=100, verbose_name='Название')),
                ('score', models.IntegerField(default=0, verbose_name='Стоимость')),
                ('img', models.FileField(default='st_img.png', upload_to='', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Вещи',
                'verbose_name_plural': 'Вещи',
            },
        ),
        migrations.CreateModel(
            name='StuffType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='Тип', max_length=100, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Тип вещей',
                'verbose_name_plural': 'Тип вещей',
            },
        ),
        migrations.AddField(
            model_name='stuff',
            name='type_stuff',
            field=models.ManyToManyField(to='lottery.StuffType', verbose_name='Тип вещей'),
        ),
        migrations.AddField(
            model_name='dotaboxmodes',
            name='stuff',
            field=models.ManyToManyField(to='lottery.Stuff', verbose_name='Вещи'),
        ),
        migrations.AddField(
            model_name='briefcases',
            name='stuff',
            field=models.ManyToManyField(to='lottery.Stuff', verbose_name='Вещи'),
        ),
    ]
