# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-01 10:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stuff',
            name='type_stuff',
        ),
        migrations.DeleteModel(
            name='StuffType',
        ),
    ]
