# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-06 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0002_auto_20170801_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuff',
            name='show_status',
            field=models.BooleanField(default=True, verbose_name='Участвует в розыгрыше'),
        ),
    ]
