# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-07 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0003_stuff_show_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuff',
            name='coins',
            field=models.IntegerField(default=0, verbose_name='RainDrop бонусы'),
        ),
    ]
