# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-07 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0004_stuff_coins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stuff',
            name='coins',
        ),
        migrations.AddField(
            model_name='briefcases',
            name='coins',
            field=models.IntegerField(default=0, verbose_name='RainDrop бонусы'),
        ),
    ]
