# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-12 18:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0005_auto_20170807_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='briefcases',
            name='coins',
        ),
    ]
