# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-13 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0006_remove_briefcases_coins'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuff',
            name='show_shop_status',
            field=models.BooleanField(default=True, verbose_name='Участвует в продаже'),
        ),
    ]
