# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-23 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0007_stuff_show_shop_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='StuffAttributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Название вещей', max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Атрибуты вещей',
                'verbose_name_plural': 'Атрибуты вещей',
            },
        ),
        migrations.CreateModel(
            name='StuffAttributesType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Название вещей', max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Типы атрибутов вещей',
                'verbose_name_plural': 'Типы атрибутов вещей',
            },
        ),
        migrations.AddField(
            model_name='stuffattributes',
            name='type',
            field=models.ManyToManyField(to='lottery.StuffAttributesType', verbose_name='Атрибуты'),
        ),
        migrations.AddField(
            model_name='stuff',
            name='attributes',
            field=models.ManyToManyField(to='lottery.StuffAttributes', verbose_name='Атрибуты'),
        ),
    ]
