# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-23 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0008_auto_20170823_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stuffattributes',
            name='type',
        ),
        migrations.AddField(
            model_name='stuffattributestype',
            name='attributes',
            field=models.ManyToManyField(to='lottery.StuffAttributes', verbose_name='Атрибуты'),
        ),
        migrations.AlterField(
            model_name='stuffattributes',
            name='title',
            field=models.CharField(default='Название атрибута', max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='stuffattributestype',
            name='title',
            field=models.CharField(default='Название типа атрибута', max_length=100, verbose_name='Название'),
        ),
    ]
